### ISSUE TITLE
[SWIFT 4.0 & XCODE 9.0] Encodable & Decodable name overlapping with buildin types

### ISSUE THREAD

**Issue by lovesuper** [wattson12/Moya-Argo#13]
Since Apple has released XCODE 9.0 & SWIFT 4.0 we obviously have problems with compiling Moya-Argo with cause of name overlapping.

[http://joxi.ru/EA4GvDUwkMlX2b.jpg](url)

**Comment by wattson12** [comment]
@lovesuper sorry about the delay, I just merged a PR covering this https://github.com/wattson12/Moya-Argo/pull/12

Haven't been able to push to cocoapods yet but pointing to master should work in the meantime
