### ISSUE TITLE
Fix CI

### ISSUE THREAD

**Issue by wattson12** [wattson12/Moya-Argo#17]
See https://github.com/wattson12/Moya-Argo/pull/16 for a short discussion

Failed build https://travis-ci.org/wattson12/Moya-Argo/builds/291330746

The last failure I see is 
```
5.55s$ pod install
Analyzing dependencies
Fetching podspec for `Moya-Argo` from `../`
[!] Unable to satisfy the following requirements:
- `Cartography` required by `Podfile`
- `Cartography (= 2.1.0)` required by `Podfile.lock`
```

No real need for cartography to be in this demo, removing that could be the first step

**Comment by kingiol** [comment]
Does the CI success, I can not see the CI Job log.

**Comment by wattson12** [comment]
The build should be public here i think https://travis-ci.org/wattson12/Moya-Argo/builds/291330746

but no, the most recent error didn't get beyond a pod install

**Comment by wattson12** [comment]
fixed as part of https://github.com/wattson12/Moya-Argo/pull/16 so closing this one
