### ISSUE TITLE
Not published to cocoapods

### ISSUE THREAD

**Issue by bitomule** [wattson12/Moya-Argo#4]
The version cocoapods install doesn't use decode. Seems like last code version still not pushed to cocoapods. Installed using git url and pulled the right version:

`pod 'Moya-Argo', :git => 'https://github.com/wattson12/Moya-Argo.git'`

**Comment by wattson12** [comment]
Hey, 

Thanks for the reminder, I will bump the cocoapods version tonight

**Comment by bitomule** [comment]
Great!

BTW, awesome job. Helped a lot.
