### ISSUE TITLE
Ambiguous reference to member "request"

### ISSUE THREAD

**Issue by bitomule** [wattson12/Moya-Argo#5]
I'm using Argo + Moya + Moya-Argo + ReactiveCocoa but I get this error:

`Ambiguous reference to member "request"`

My code is:

```
let provider:ReactiveCocoaMoyaProvider<MyAPI> = ReactiveCocoaMoyaProvider(stubClosure: { _ in return .Immediate })
provider.request(.User(id: "24"))
        .mapObject("user")
        .observeOn(UIScheduler())
        .start { event in
            expectation.fulfill()
            switch event {
            case .Next(let user):
                XCTAssertNotNil(user)
                XCTAssertEqual(user.id, 1)
            case .Failed(let error):
                XCTFail("Error mapping user: \(error)")
            default: break
            }

    }
```

And yes, It's running inside a XCTest.

Issue is fixed if I don't import Moya and only import Moya_Argo but then I get the error that ReactiveCocoaMoyaProvider doesn't exist.

Any idea on how  to fix it?

**Comment by bitomule** [comment]
Ok, fixed it by changing:

`.mapObject("user")`

to

`.mapObject(User.self,rootKey: "user")`

**Comment by wattson12** [comment]
OK cool I was just taking a look, I find that when there are chains of these reactive functions swift likes to report the first one as being ambiguous, even if the issue comes later, so the usual first step is to explicitly tell the compiler which types I am expecting at each state
